如果装饰的是个类方法，需要在调用 func 时添加 self 参数， 因为类方法的第一个参数是 self。 否则会报 TypeError: bar() missing 1 required positional argument: 'x' 错误。但是这样加了之后，这个用作装饰器的类，装饰 function 的时候又会出错